{
 "title": "intersight-cl-emea-24",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Security Advisories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "intersight_advisories_security_count{}"
    }
   ]
  },
  {
   "title": "Objects with Security Advisories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "intersight_advisories_security_affected_objects{}"
    }
   ]
  },
  {
   "title": "Objects with other advisories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "intersight_advisories_nonsecurity_affected_objects{}"
    }
   ]
  },
  {
   "title": "NTP Policy Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "intersight_policy_ntp_count{}" }
   ]
  },
  {
   "title": "Virtual Machine Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "intersight_vm_count{}" }
   ]
  },
  { "title": "Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Intersight Total Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(intersight_alarms_count)", "legendFormat": "Intersight Total Alarms" }
   ]
  },
  {
   "title": "Intersight Critical Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "intersight_alarms_count{severity=\"critical\"}"
    }
   ]
  },
  {
   "title": "Intersight Warning Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "intersight_alarms_count{severity=\"warning\"}"
    }
   ]
  },
  { "title": "UCS Environmentals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "UCS Host Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "intersight_ucs_host_power{}", "legendFormat": "{{intersight_name}}" }
   ]
  },
  {
   "title": "UCS Host Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "intersight_ucs_host_temperature{}",
     "legendFormat": "{{intersight_host_name}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "intersight_ucs_fan_speed{}", "legendFormat": "{{intersight_host_name}}" }
   ]
  },
  { "title": "UCS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "UCS Network Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "intersight_ucs_network_utilization_average{}",
     "legendFormat": "{{intersight_host_name}}"
    }
   ]
  },
  {
   "title": "UCS Network TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "intersight_ucs_network_transmit_rate{}",
     "legendFormat": "{{intersight_host_name}}"
    }
   ]
  },
  {
   "title": "UCS Network RX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "intersight_ucs_network_receive_rate{}",
     "legendFormat": "{{intersight_host_name}}"
    }
   ]
  },
  { "title": "HyperFlex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Hyperflex IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "intersight_hyperflex_read_iops{}"
    },
    {
     "expr": "intersight_hyperflex_write_iops{}"
    }
   ]
  },
  {
   "title": "HyperFlex Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "intersight_hyperflex_read_throughput{}"
    },
    {
     "expr": "intersight_hyperflex_write_throughput{}"
    }
   ]
  },
  {
   "title": "HyperFlex Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "intersight_hyperflex_read_latency{}"
    },
    {
     "expr": "intersight_hyperflex_write_latency{}"
    }
   ]
  }
 ]
}